version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./src:/app/src
  redis:
    image: redis:6.2
    volumes:
      - redisdata:/data
    restart: unless-stopped
volumes:
  redisdata: